### PR TITLE
update for compatibility with freemarker 2.3.22

### PR DESCRIPTION
**Pull request by thecodemaker**
Hello Chris, 

Your work is appreciated in regards to freemarker-introspection. Please take into consideration my changes in regards to compatibility with freemarker 2.3.22. 

Looking forward for your feedback. 

Best regards,
Bogdan

### CODE REVIEW

**Comment by cwong15** [comment]
Hello Bogdan. Thank you very much for your contribution! While your efforts are very much appreciated, the main line of development is in currently in the packagelocal branch. This branch takes advantage of package local accessors in the newer versions of Freemarker which makes it no longer necessary to keep track of internal field names. This should make freemarker-introspection more robust and compatible with future versions of freemarker. Feel free to try out the packagelocal branch. Rest assured I will endeavor to update freemarker-introspection to be compatible with freemarker 2.3.22, if it is not already compatible.

**Comment by thecodemaker** [comment]
Hello Christopher, 

Thank you for your reply. It was my pleasure :). I will use the code version from branch packagelocal as you suggested. Hope it is ok if I let you know if I have other questions.

Best regards,
Bogdan

**Comment by cwong15** [comment]
For what it’s worth, I just updated the mainline (master) branch on Github with the stuff from packagelocal. In other words, freemarker-introspection mainline should support the latest Freemarker now.

**Comment by cwong15** [comment]
Closing this pull request now, because mainline will now use the packagelocal approach to achieve FM 2.3.22 compatibility. Again, thank you Bogdan.

**Comment by thecodemaker** [comment]
Thank you!

**Pull request closed without merging**
